# Generated by Django 4.1.2 on 2022-11-30 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_mame', models.TextField(max_length=30)),
                ('pro_picture', models.ImageField(upload_to='profile')),
                ('pro_updated', models.DateTimeField(auto_now=True)),
                ('pro_created', models.DateTimeField(auto_now=True)),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
