# Generated by Django 4.1.2 on 2022-11-30 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conservation',
            fields=[
                ('cons_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_text', models.TextField()),
                ('cons_date', models.DateField(auto_now=True)),
                ('cons_time', models.TimeField(auto_now=True)),
                ('cons_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('cons_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
