# Generated by Django 4.1.2 on 2022-12-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_profile_pro_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pro_mame',
            new_name='pro_name',
        ),
    ]
