# Generated by Django 4.1.2 on 2022-12-06 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_rename_pro_mame_profile_pro_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservation',
            name='cons_date',
        ),
        migrations.RemoveField(
            model_name='conservation',
            name='cons_text',
        ),
        migrations.RemoveField(
            model_name='conservation',
            name='cons_time',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_text', models.TextField(max_length=500)),
                ('chat_time', models.TimeField(auto_now=True)),
                ('chat_date', models.DateField(auto_now=True)),
                ('chat_conservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conservation')),
                ('chat_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
